---
- name: Crear Clave SSH para Fernando
  hosts: node1
  become: yes
  tasks:
  - name: Creamos una clave ssh de 2048-bit para el usuario fernando en el directorio ~fernando/.ssh/id_rsa
    ansible.builtin.user:
      name: fernando
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh_temporal/id_rsa